[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-l --cov=ghfailwx --cov-report=xml"
testpaths = [
    "tests",
]
filterwarnings = "ignore::DeprecationWarning"
